### ISSUE TITLE
error when building, unsupported

### ISSUE THREAD

**Issue by saesky** [ConnectyCube/connectycube-web-samples#266]
when I trying to build with npm run build, the error message 

> videochat@2.0.0 start
> webpack-dev-server --env.development

i ｢wds｣: Project is running at https://localhost:3000/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\work\connectycube-web-samples-master\videochat\, D:\work\connectycube-web-samples-master\videochat\dist
i ｢wds｣: 404s will fallback to /index.html
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\work\connectycube-web-samples-master\videochat\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\work\connectycube-web-samples-master\videochat\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\work\connectycube-web-samples-master\videochat\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\work\connectycube-web-samples-master\videochat\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\work\connectycube-web-samples-master\videochat\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\work\connectycube-web-samples-master\videochat\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\work\connectycube-web-samples-master\videochat\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\work\connectycube-web-samples-master\videochat\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\work\connectycube-web-samples-master\videochat\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\work\connectycube-web-samples-master\videochat\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by DaveLomber** [comment]
@saesky it seems it's related to Node.js version. Can you try Node 14?

**Comment by DaveLomber** [comment]
The above issue is related to when using Node > 14.

The very recent version of video chat sample now should work well with Node 20/22
